# Generated by Django 4.1 on 2022-08-25 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField()),
                ('emp_stat', models.TextField()),
                ('skill', models.TextField()),
                ('hobbies', models.TextField()),
                ('courses', models.TextField()),
                ('extracurricular', models.TextField()),
                ('achievements', models.TextField()),
                ('passion', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('processed', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
