# Generated by Django 4.1 on 2022-08-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
