# Generated by Django 4.1 on 2022-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0002_delete_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.TextField()),
                ('emp_stat', models.TextField()),
                ('skill', models.TextField()),
                ('hobbies', models.TextField()),
                ('courses', models.TextField()),
                ('extracurricular', models.TextField()),
                ('achievements', models.TextField()),
                ('passion', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
