# Generated by Django 4.1 on 2022-08-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('intermediate', models.CharField(max_length=100)),
                ('bachelors', models.CharField(max_length=100)),
            ],
        ),
    ]
